-- MySQL Script generated by MySQL Workbench
-- Mon May 26 22:05:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `delivery` ;

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`restaurante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`restaurante` ;

CREATE TABLE IF NOT EXISTS `delivery`.`restaurante` (
  `id_restaurante` INT NOT NULL AUTO_INCREMENT,
  `nome_rest` VARCHAR(50) NULL,
  `taxa_entrega` FLOAT NULL,
  `nota_med_restaurante` FLOAT NULL,
  `faixa_preco` INT NULL,
  PRIMARY KEY (`id_restaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`usuario` ;

CREATE TABLE IF NOT EXISTS `delivery`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NULL,
  `cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`entregador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`entregador` ;

CREATE TABLE IF NOT EXISTS `delivery`.`entregador` (
  `id_entregador` INT NOT NULL AUTO_INCREMENT,
  `nome_entregador` VARCHAR(100) NULL,
  `cnh` VARCHAR(11) NULL,
  `cpf` VARCHAR(11) NULL,
  `nota_media_entregador` FLOAT NULL,
  PRIMARY KEY (`id_entregador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`prato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`prato` ;

CREATE TABLE IF NOT EXISTS `delivery`.`prato` (
  `id_prato` INT NOT NULL AUTO_INCREMENT,
  `preco` FLOAT NULL,
  `nome_prato` VARCHAR(50) NULL,
  `descricao` VARCHAR(200) NULL,
  `restaurante_id_restaurante` INT NOT NULL,
  PRIMARY KEY (`id_prato`, `restaurante_id_restaurante`),
  INDEX `fk_prato_restaurante1_idx` (`restaurante_id_restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_prato_restaurante1`
    FOREIGN KEY (`restaurante_id_restaurante`)
    REFERENCES `delivery`.`restaurante` (`id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`endereco` ;

CREATE TABLE IF NOT EXISTS `delivery`.`endereco` (
  `cep` VARCHAR(8) NOT NULL,
  `num_end` INT NOT NULL,
  `rua` VARCHAR(100) NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(2) NULL,
  `entregador_id_entregador` INT NULL,
  `restaurante_id_restaurante` INT NULL,
  PRIMARY KEY (`cep`, `num_end`),
  INDEX `fk_endereco_entregador_idx` (`entregador_id_entregador` ASC) VISIBLE,
  INDEX `fk_endereco_restaurante1_idx` (`restaurante_id_restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_entregador`
    FOREIGN KEY (`entregador_id_entregador`)
    REFERENCES `delivery`.`entregador` (`id_entregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_restaurante1`
    FOREIGN KEY (`restaurante_id_restaurante`)
    REFERENCES `delivery`.`restaurante` (`id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`telefone` ;

CREATE TABLE IF NOT EXISTS `delivery`.`telefone` (
  `num_tel` VARCHAR(11) NOT NULL,
  `entregador_id_entregador` INT NULL,
  `restaurante_id_restaurante` INT NULL,
  `usuario_id_usuario` INT NULL,
  PRIMARY KEY (`num_tel`),
  INDEX `fk_telefone_entregador1_idx` (`entregador_id_entregador` ASC) VISIBLE,
  INDEX `fk_telefone_restaurante1_idx` (`restaurante_id_restaurante` ASC) VISIBLE,
  INDEX `fk_telefone_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_entregador1`
    FOREIGN KEY (`entregador_id_entregador`)
    REFERENCES `delivery`.`entregador` (`id_entregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_restaurante1`
    FOREIGN KEY (`restaurante_id_restaurante`)
    REFERENCES `delivery`.`restaurante` (`id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `delivery`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`usuario_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`usuario_has_endereco` ;

CREATE TABLE IF NOT EXISTS `delivery`.`usuario_has_endereco` (
  `id_usuario_endereco` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `endereco_cep` VARCHAR(8) NOT NULL,
  `endereco_num_end` INT NOT NULL,
  PRIMARY KEY (`id_usuario_endereco`, `usuario_id_usuario`, `endereco_cep`, `endereco_num_end`),
  INDEX `fk_usuario_has_endereco_endereco1_idx` (`endereco_cep` ASC, `endereco_num_end` ASC) VISIBLE,
  INDEX `fk_usuario_has_endereco_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_endereco_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `delivery`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_endereco_endereco1`
    FOREIGN KEY (`endereco_cep` , `endereco_num_end`)
    REFERENCES `delivery`.`endereco` (`cep` , `num_end`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`pedido` ;

CREATE TABLE IF NOT EXISTS `delivery`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NULL,
  `recebido` DATETIME NULL,
  `inicio_preparo` DATETIME NULL,
  `saida` DATETIME NULL,
  `entrega` DATETIME NULL,
  `restaurante_id_restaurante` INT NOT NULL,
  `entregador_id_entregador` INT NOT NULL,
  `id_usuario_endereco` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `restaurante_id_restaurante`, `entregador_id_entregador`, `id_usuario_endereco`),
  INDEX `fk_pedido_restaurante1_idx` (`restaurante_id_restaurante` ASC) VISIBLE,
  INDEX `fk_pedido_entregador1_idx` (`entregador_id_entregador` ASC) VISIBLE,
  INDEX `fk_pedido_usuario_has_endereco1_idx` (`id_usuario_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_restaurante1`
    FOREIGN KEY (`restaurante_id_restaurante`)
    REFERENCES `delivery`.`restaurante` (`id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_entregador1`
    FOREIGN KEY (`entregador_id_entregador`)
    REFERENCES `delivery`.`entregador` (`id_entregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario_has_endereco1`
    FOREIGN KEY (`id_usuario_endereco`)
    REFERENCES `delivery`.`usuario_has_endereco` (`id_usuario_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`pedido_has_prato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`pedido_has_prato` ;

CREATE TABLE IF NOT EXISTS `delivery`.`pedido_has_prato` (
  `pedido_id_pedido` INT NOT NULL,
  `prato_id_prato` INT NOT NULL,
  PRIMARY KEY (`pedido_id_pedido`, `prato_id_prato`),
  INDEX `fk_pedido_has_prato_prato1_idx` (`prato_id_prato` ASC) VISIBLE,
  INDEX `fk_pedido_has_prato_pedido1_idx` (`pedido_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_prato_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `delivery`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_prato_prato1`
    FOREIGN KEY (`prato_id_prato`)
    REFERENCES `delivery`.`prato` (`id_prato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `delivery`.`pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `horario_pagto` DATETIME NULL,
  `forma_pagto` VARCHAR(10) NULL,
  `valor` FLOAT NULL,
  `pedido_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pagamento`, `pedido_id_pedido`),
  INDEX `fk_pagamento_pedido1_idx` (`pedido_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `delivery`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `delivery`.`avaliacao` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `nota_restaurante` FLOAT NULL,
  `nota_entregador` FLOAT NULL,
  `comentario` VARCHAR(200) NULL,
  `usuario_id_usuario` INT NOT NULL,
  `pedido_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`, `usuario_id_usuario`, `pedido_id_pedido`),
  INDEX `fk_avaliacao_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_avaliacao_pedido1_idx` (`pedido_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `delivery`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `delivery`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
