package provab2;

import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author jvalb
 */
public class ProvaB2 extends javax.swing.JFrame implements MessageEventListener {
    
    int s = 20;
    int d = 5;
    int x = 200;
    int y = 150;
    Color playerColor = Color.GREEN;
    
    // Criando a bolinha controlada por Thread com valores aleeatórios de s e d
    int sT = (int) (Math.random()*(90-10 + 1) + 10);
    int dT = (int) (Math.random()*(18-3 + 1) + 3);
    int xT = 300;
    int yT = 250;
    Color compColor = Color.RED;

    public ProvaB2() {
        initComponents();
        jPanel1.requestFocus();
        new Thread(comportamentoComp).start();
    }
    
    BPlayer player = new BPlayer(s, d, x, y);
    BComp comp = new BComp(sT, dT, xT, yT, this);
    
    boolean colidiu = false;
    
    @Override
    public void messageArrived(MessageEvent e) {
        colidiu = true;
    }
    
    
    // Coloquei a bolinha para rodar num runnable criado aqui porque, dentro dela, ficava difícil de passar o tamanho da tela caso fosse reajustada
    Runnable comportamentoComp = new Runnable() {
        @Override
        public void run() {
            while (true) {
                int soma = 0;
                int[] probs = comp.getProbs();
                for (int i = 0; i < probs.length; i++) {
                    soma += probs[i];
                }
                
                int height = jPanel1.getHeight();
                int width = jPanel1.getWidth();
                
                // Número de repetições do input
                int l = (int) (Math.random()*(40-1 + 1) + 1);
                
                // Valor aleatório que, de acordo com os intervalos da BComp, corresponderá a um input
                int tecla = (int) (Math.random()*(soma-0 + 1) + 0);
                System.out.println(l);
                for (int j = 0; j < l; j++) {
                    comp.processarInput(tecla, height, width, player.getX(), player.getY(), player.getS());
                    jPanel1.repaint();
                    if (colidiu == true) {
                        j = 41;
                        // Se colidiu, para de dar esse input
                        colidiu = false;
                        System.out.println("COLIDIU");
                    }
                    try {
                        Thread.sleep(100); // dá um sleep de 0,1s porque senão os movimentos são instantâneos
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ProvaB2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                try {
                    int t = (int) (Math.random()*(600-500 + 1) + 500); // Faz o sleep de 0,5s ou um pouquinho mais
                    Thread.sleep(t);
                } catch (InterruptedException ex) {
                }
            }
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel() {
            public void paint(Graphics g) {
                super.paint(g);
                player.pintaBolinha(g, playerColor);
                comp.pintaBolinha(g, compColor);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // Evento de input do usuário
        
        int tecla = evt.getKeyCode();
        int height = jPanel1.getHeight();
        int width = jPanel1.getWidth();
        
        player.processarInput(tecla, height, width, comp.getX(), comp.getY(), comp.getS());
        this.repaint();
    }//GEN-LAST:event_jPanel1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProvaB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProvaB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProvaB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProvaB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProvaB2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
