-- MySQL Script generated by MySQL Workbench
-- Tue Apr  1 12:12:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica` ;

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica` DEFAULT CHARACTER SET utf8 ;
USE `clinica` ;

-- -----------------------------------------------------
-- Table `clinica`.`tutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`tutor` ;

CREATE TABLE IF NOT EXISTS `clinica`.`tutor` (
  `cpf_tutor` VARCHAR(11) NOT NULL,
  `nome_tutor` VARCHAR(45) NULL,
  `data_nasc_tutor` VARCHAR(45) NULL,
  `email_tutor` VARCHAR(45) NULL,
  `excluido` TINYINT NULL,
  `senha_tutor` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf_tutor`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf_tutor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`veterinario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`veterinario` ;

CREATE TABLE IF NOT EXISTS `clinica`.`veterinario` (
  `id_veterinario` VARCHAR(15) NOT NULL,
  `nome_vet` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  `excluido` TINYINT NULL,
  `senha_vet` VARCHAR(45) NULL,
  PRIMARY KEY (`id_veterinario`),
  UNIQUE INDEX `id_veterinario_UNIQUE` (`id_veterinario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`telefone` ;

CREATE TABLE IF NOT EXISTS `clinica`.`telefone` (
  `numtel` VARCHAR(15) NOT NULL,
  `tutor_cpf_tutor` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`numtel`, `tutor_cpf_tutor`),
  INDEX `fk_telefone_tutor_idx` (`tutor_cpf_tutor` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_tutor`
    FOREIGN KEY (`tutor_cpf_tutor`)
    REFERENCES `clinica`.`tutor` (`cpf_tutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`endereco` ;

CREATE TABLE IF NOT EXISTS `clinica`.`endereco` (
  `cep` VARCHAR(8) NOT NULL,
  `num_end` INT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`endereco_has_tutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`endereco_has_tutor` ;

CREATE TABLE IF NOT EXISTS `clinica`.`endereco_has_tutor` (
  `endereco_cep` VARCHAR(8) NOT NULL,
  `tutor_cpf_tutor` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`endereco_cep`, `tutor_cpf_tutor`),
  INDEX `fk_endereco_has_tutor_tutor1_idx` (`tutor_cpf_tutor` ASC) VISIBLE,
  INDEX `fk_endereco_has_tutor_endereco1_idx` (`endereco_cep` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_has_tutor_endereco1`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `clinica`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_has_tutor_tutor1`
    FOREIGN KEY (`tutor_cpf_tutor`)
    REFERENCES `clinica`.`tutor` (`cpf_tutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`animal` ;

CREATE TABLE IF NOT EXISTS `clinica`.`animal` (
  `id_animal` VARCHAR(15) NOT NULL,
  `nome_animal` VARCHAR(45) NULL,
  `data_nasc_animal` DATE NULL,
  `especie` VARCHAR(45) NULL,
  `raca` VARCHAR(45) NULL,
  `porte` VARCHAR(45) NULL,
  `peso` FLOAT NULL,
  `obs` VARCHAR(100) NULL,
  `excluido` TINYINT NULL,
  PRIMARY KEY (`id_animal`),
  UNIQUE INDEX `id_animal_UNIQUE` (`id_animal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`tutor_has_animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`tutor_has_animal` ;

CREATE TABLE IF NOT EXISTS `clinica`.`tutor_has_animal` (
  `tutor_cpf_tutor` VARCHAR(11) NOT NULL,
  `animal_id_animal` VARCHAR(15) NOT NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`tutor_cpf_tutor`, `animal_id_animal`),
  INDEX `fk_tutor_has_animal_animal1_idx` (`animal_id_animal` ASC) VISIBLE,
  INDEX `fk_tutor_has_animal_tutor1_idx` (`tutor_cpf_tutor` ASC) VISIBLE,
  CONSTRAINT `fk_tutor_has_animal_tutor1`
    FOREIGN KEY (`tutor_cpf_tutor`)
    REFERENCES `clinica`.`tutor` (`cpf_tutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutor_has_animal_animal1`
    FOREIGN KEY (`animal_id_animal`)
    REFERENCES `clinica`.`animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`servico` ;

CREATE TABLE IF NOT EXISTS `clinica`.`servico` (
  `id_servico` VARCHAR(15) NOT NULL,
  `nome_serv` VARCHAR(45) NULL,
  `custo_base` FLOAT NULL,
  `especificacoes` VARCHAR(100) NULL,
  PRIMARY KEY (`id_servico`),
  UNIQUE INDEX `id_servico_UNIQUE` (`id_servico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`consulta` ;

CREATE TABLE IF NOT EXISTS `clinica`.`consulta` (
  `id_consulta` VARCHAR(15) NOT NULL,
  `inicio` DATETIME NULL,
  `termino` DATETIME NULL,
  `obs` VARCHAR(100) NULL,
  `animal_id_animal` VARCHAR(15) NOT NULL,
  `veterinario_id_veterinario` VARCHAR(15) NOT NULL,
  `servico_id_servico` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_consulta`, `animal_id_animal`, `veterinario_id_veterinario`, `servico_id_servico`),
  UNIQUE INDEX `id_consulta_UNIQUE` (`id_consulta` ASC) VISIBLE,
  INDEX `fk_consulta_animal1_idx` (`animal_id_animal` ASC) VISIBLE,
  INDEX `fk_consulta_veterinario1_idx` (`veterinario_id_veterinario` ASC) VISIBLE,
  INDEX `fk_consulta_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_animal1`
    FOREIGN KEY (`animal_id_animal`)
    REFERENCES `clinica`.`animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_veterinario1`
    FOREIGN KEY (`veterinario_id_veterinario`)
    REFERENCES `clinica`.`veterinario` (`id_veterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `clinica`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`vacina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`vacina` ;

CREATE TABLE IF NOT EXISTS `clinica`.`vacina` (
  `id_vacina` INT NOT NULL,
  `nome_vacina` VARCHAR(45) NULL,
  `validade` INT NULL,
  PRIMARY KEY (`id_vacina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`nota` ;

CREATE TABLE IF NOT EXISTS `clinica`.`nota` (
  `id_nota` VARCHAR(15) NOT NULL,
  `valor_pago` FLOAT NULL,
  `forma_pagto` VARCHAR(45) NULL,
  `notacol` VARCHAR(45) NULL,
  `obs` VARCHAR(45) NULL,
  `tutor_cpf_tutor` VARCHAR(11) NOT NULL,
  `consulta_id_consulta` VARCHAR(15) NOT NULL,
  `consulta_animal_id_animal` VARCHAR(15) NOT NULL,
  `consulta_veterinario_id_veterinario` VARCHAR(15) NOT NULL,
  `consulta_servico_id_servico` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_nota`, `tutor_cpf_tutor`, `consulta_id_consulta`, `consulta_animal_id_animal`, `consulta_veterinario_id_veterinario`, `consulta_servico_id_servico`),
  UNIQUE INDEX `id_nota_UNIQUE` (`id_nota` ASC) VISIBLE,
  INDEX `fk_nota_tutor1_idx` (`tutor_cpf_tutor` ASC) VISIBLE,
  INDEX `fk_nota_consulta1_idx` (`consulta_id_consulta` ASC, `consulta_animal_id_animal` ASC, `consulta_veterinario_id_veterinario` ASC, `consulta_servico_id_servico` ASC) VISIBLE,
  CONSTRAINT `fk_nota_tutor1`
    FOREIGN KEY (`tutor_cpf_tutor`)
    REFERENCES `clinica`.`tutor` (`cpf_tutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_consulta1`
    FOREIGN KEY (`consulta_id_consulta` , `consulta_animal_id_animal` , `consulta_veterinario_id_veterinario` , `consulta_servico_id_servico`)
    REFERENCES `clinica`.`consulta` (`id_consulta` , `animal_id_animal` , `veterinario_id_veterinario` , `servico_id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`animal_has_vacina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica`.`animal_has_vacina` ;

CREATE TABLE IF NOT EXISTS `clinica`.`animal_has_vacina` (
  `animal_id_animal` VARCHAR(15) NOT NULL,
  `vacina_id_vacina` INT NOT NULL,
  `data_vac` DATETIME NULL,
  `data_validade` DATETIME NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`animal_id_animal`, `vacina_id_vacina`),
  INDEX `fk_animal_has_vacina_vacina1_idx` (`vacina_id_vacina` ASC) VISIBLE,
  INDEX `fk_animal_has_vacina_animal1_idx` (`animal_id_animal` ASC) VISIBLE,
  CONSTRAINT `fk_animal_has_vacina_animal1`
    FOREIGN KEY (`animal_id_animal`)
    REFERENCES `clinica`.`animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_has_vacina_vacina1`
    FOREIGN KEY (`vacina_id_vacina`)
    REFERENCES `clinica`.`vacina` (`id_vacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
