-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 22:28:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `concessionaria` ;

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concessionaria` DEFAULT CHARACTER SET utf8 ;
USE `concessionaria` ;

-- -----------------------------------------------------
-- Table `concessionaria`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`contato` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`contato` (
  `id_contato` INT NOT NULL,
  `tel_1` VARCHAR(45) NULL,
  `tel_2` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`marca` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_montadora` VARCHAR(45) NOT NULL,
  `origem` VARCHAR(15) NOT NULL,
  `contato_id_contato` INT NOT NULL,
  PRIMARY KEY (`id_marca`),
  UNIQUE INDEX `id_marca_UNIQUE` (`id_marca` ASC) VISIBLE,
  INDEX `fk_marca_contato1_idx` (`contato_id_contato` ASC) VISIBLE,
  CONSTRAINT `fk_marca_contato1`
    FOREIGN KEY (`contato_id_contato`)
    REFERENCES `concessionaria`.`contato` (`id_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`veiculo` (
  `renavam` VARCHAR(15) NOT NULL,
  `chassi` VARCHAR(20) NULL,
  `modelo` VARCHAR(45) NULL,
  `ano_modelo` INT NULL,
  `ano_fabricacao` INT NULL,
  `cor` VARCHAR(45) NULL,
  `potencia` INT NULL,
  `placa` VARCHAR(10) NULL,
  `capacidade` INT NULL,
  `valor_fipe` FLOAT NULL,
  `tipo_combustivel` VARCHAR(45) NULL,
  `marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`renavam`),
  INDEX `fk_veiculo_marca_idx` (`marca_id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_marca`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `concessionaria`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`endereco` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`endereco` (
  `cep` VARCHAR(15) NOT NULL,
  `numero_end` INT NOT NULL,
  `rua` VARCHAR(100) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`cep`, `numero_end`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`unidade` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`unidade` (
  `id_unidade` INT NOT NULL,
  `nome_unidade` VARCHAR(45) NULL,
  `contato_id_contato` INT NOT NULL,
  `endereco_cep` VARCHAR(15) NOT NULL,
  `endereco_numero_end` INT NOT NULL,
  PRIMARY KEY (`id_unidade`),
  INDEX `fk_unidade_contato1_idx` (`contato_id_contato` ASC) VISIBLE,
  INDEX `fk_unidade_endereco1_idx` (`endereco_cep` ASC, `endereco_numero_end` ASC) VISIBLE,
  CONSTRAINT `fk_unidade_contato1`
    FOREIGN KEY (`contato_id_contato`)
    REFERENCES `concessionaria`.`contato` (`id_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_endereco1`
    FOREIGN KEY (`endereco_cep` , `endereco_numero_end`)
    REFERENCES `concessionaria`.`endereco` (`cep` , `numero_end`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`vendedor` (
  `id_vendedor` INT NOT NULL,
  `nome_vendedor` VARCHAR(45) NULL,
  `data_nasc_vendedor` DATE NULL,
  `contato_id_contato` INT NOT NULL,
  `unidade_id_unidade` INT NOT NULL,
  PRIMARY KEY (`id_vendedor`),
  INDEX `fk_vendedor_contato1_idx` (`contato_id_contato` ASC) VISIBLE,
  INDEX `fk_vendedor_unidade1_idx` (`unidade_id_unidade` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor_contato1`
    FOREIGN KEY (`contato_id_contato`)
    REFERENCES `concessionaria`.`contato` (`id_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_unidade1`
    FOREIGN KEY (`unidade_id_unidade`)
    REFERENCES `concessionaria`.`unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`comprador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`comprador` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`comprador` (
  `cpf_cnpj_comprador` VARCHAR(30) NOT NULL,
  `nome_comprador` VARCHAR(100) NULL,
  `data_nasc_comprador` DATE NULL,
  `responsavel_pj` VARCHAR(45) NULL,
  `contato_id_contato` INT NOT NULL,
  `endereco_cep` VARCHAR(15) NOT NULL,
  `endereco_numero_end` INT NOT NULL,
  PRIMARY KEY (`cpf_cnpj_comprador`),
  INDEX `fk_comprador_contato1_idx` (`contato_id_contato` ASC) VISIBLE,
  INDEX `fk_comprador_endereco1_idx` (`endereco_cep` ASC, `endereco_numero_end` ASC) VISIBLE,
  CONSTRAINT `fk_comprador_contato1`
    FOREIGN KEY (`contato_id_contato`)
    REFERENCES `concessionaria`.`contato` (`id_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprador_endereco1`
    FOREIGN KEY (`endereco_cep` , `endereco_numero_end`)
    REFERENCES `concessionaria`.`endereco` (`cep` , `numero_end`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`venda` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `valor_venda` FLOAT NULL,
  `forma_pagto` VARCHAR(45) NULL,
  `comissao` FLOAT NULL,
  `data_hora_compra` DATETIME NULL,
  `vendedor_id_vendedor` INT NOT NULL,
  `comprador_cpf_cnpj_comprador` VARCHAR(30) NOT NULL,
  `veiculo_renavam` VARCHAR(15) NOT NULL,
  `unidade_id_unidade` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_vendedor1_idx` (`vendedor_id_vendedor` ASC) VISIBLE,
  INDEX `fk_venda_comprador1_idx` (`comprador_cpf_cnpj_comprador` ASC) VISIBLE,
  INDEX `fk_venda_veiculo1_idx` (`veiculo_renavam` ASC) VISIBLE,
  INDEX `fk_venda_unidade1_idx` (`unidade_id_unidade` ASC) VISIBLE,
  CONSTRAINT `fk_venda_vendedor1`
    FOREIGN KEY (`vendedor_id_vendedor`)
    REFERENCES `concessionaria`.`vendedor` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_comprador1`
    FOREIGN KEY (`comprador_cpf_cnpj_comprador`)
    REFERENCES `concessionaria`.`comprador` (`cpf_cnpj_comprador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_veiculo1`
    FOREIGN KEY (`veiculo_renavam`)
    REFERENCES `concessionaria`.`veiculo` (`renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_unidade1`
    FOREIGN KEY (`unidade_id_unidade`)
    REFERENCES `concessionaria`.`unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`historico_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concessionaria`.`historico_venda` ;

CREATE TABLE IF NOT EXISTS `concessionaria`.`historico_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `valor_venda` FLOAT NULL,
  `forma_pagto` VARCHAR(45) NULL,
  `comissao` FLOAT NULL,
  `data_hora_compra` DATETIME NULL,
  `vendedor_id_vendedor` INT NULL,
  `comprador_cpf_cnpj_comprador` VARCHAR(30) NULL,
  `veiculo_renavam` VARCHAR(15) NULL,
  `unidade_id_unidade` INT NULL,
  `historico_vendacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_venda`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
