-- MySQL Script generated by MySQL Workbench
-- Wed May 21 22:46:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- ------------------id_aluno-----------------------------------
-- Schema escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escola` ;

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8 ;
USE `escola` ;

-- -----------------------------------------------------
-- Table `escola`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola`.`curso` ;

CREATE TABLE IF NOT EXISTS `escola`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curso`),
  UNIQUE INDEX `id_curso_UNIQUE` (`id_curso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola`.`professor` ;

CREATE TABLE IF NOT EXISTS `escola`.`professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome_professor` VARCHAR(100) NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_professor`, `curso_id_curso`),
  UNIQUE INDEX `id_professor_UNIQUE` (`id_professor` ASC) VISIBLE,
  INDEX `fk_professor_curso_idx` (`curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_professor_curso`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escola`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola`.`aluno` ;

CREATE TABLE IF NOT EXISTS `escola`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(100) NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_aluno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`aluno_has_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola`.`aluno_has_curso` ;

CREATE TABLE IF NOT EXISTS `escola`.`aluno_has_curso` (
  `aluno_id_aluno` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  `nota` FLOAT NULL,
  PRIMARY KEY (`aluno_id_aluno`, `curso_id_curso`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`curso_id_curso` ASC) VISIBLE,
  INDEX `fk_aluno_has_curso_aluno1_idx` (`aluno_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_curso_aluno1`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escola`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escola`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
